print('tom work hard......')
print('tom work hard......')
print('tom work hard......')
print('tom work hard......')
print('tom work hard......')
print('tom work hard......')
print('tom work hard......')